[licenses]
allow = [
    "Apache-2.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "bitflags", version = "1.3.2" },
    { name = "foldhash", version = "0.1.5" },
    { name = "hashbrown", version = "0.15.5" },
    { name = "thiserror", version = "1.0.69" },
    { name = "thiserror-impl", version = "1.0.69" },
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"

[advisories]
ignore = [
    # paste is unmaintained, but is complete.
    "RUSTSEC-2024-0436",
]
